version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - apt-get update
      - apt-get -y upgrade
      - apt-get install xvfb python python-pip build-essential -y
      - pip install --upgrade pip
      - pip install flask
      - pip install faker
      - pip install flask_wtf
      - pip install wtforms
  build:
    commands:
      - python3 main.py
artifacts:
  files:
    - '**/*'
  base-directory: 'target/my-web-app'
